### ISSUE TITLE
Problems on Build Kernel Step 1

### ISSUE THREAD

**Issue by Special-Niewbie** [thefloppydriver/pc2drc#1] opened 2022-03-03 16:24 UTC
**Describe the bug**
Hello @thefloppydriver ,

first of all congratulations for the project I love very much and I hope you are registered in the GBAtemp Forum, and  if you have posted this news of this project there?
Because in my opinion, this is a very important project and will make many people happy about (if you don't, I will do it for you). 

Anyway, I am testing PC2DRC via a notebook that I use for testing, but unfortunately I can't go forward over to Stage 1 to build a new 5.11.22 kernel; and the error says (half in my language/ half in English) "impossible to read the module.order: File or Directory doesn't exist" ... and that I have to run the Make function before the Make install function.
Any idea why about that (I try to post the picture below

**To Reproduce**
1. After start Stage 1, with frash installation of Ubuntu 20.04

**Screenshots**
![IMG_20220301_123624](https://user-images.githubusercontent.com/64843123/156604237-7aad82bf-de11-4e9b-a4ce-667e73d35cd6.jpg)

**Desktop (please complete the following information):**
 - OS:  Ubuntu 20.04 LTS
 - System Architecture  x86_64

**Comment by thefloppydriver** [comment] 2022-03-03 17:24
Yk what- It might be a problem with make oldconfig. I'll take a look at it and get back to you.

**Comment by thefloppydriver** [comment] 2022-03-03 18:25
It's fixed. However, you should wait just a bit before cloning and running this because I'm about to remove the need to recompile the entire kernel. I'll post an update here once I've done that.

**Comment by thefloppydriver** [comment] 2022-03-05 00:13
@Special-Niewbie Hello. I've been doing quite a bit of testing and I'm fairly certain that it's safe to run EXPERIMENTAL-stage-1-kernel-patch.sh instead of stage-1-kernel patch.sh. All other commands can be run normally. If you have any trouble running EXPERIMENTAL-stage-1-kernel-patch.sh, just run stage-1-kernel-patch.sh. Both of them work just fine, the EXPERIMENTAL one is a lot faster, though (an hour or more faster.)

**Comment by Special-Niewbie** [comment] 2022-03-05 00:57
> @Special-Niewbie Hello. I've been doing quite a bit of testing and I'm fairly certain that it's safe to run EXPERIMENTAL-stage-1-kernel-patch.sh instead of stage-1-kernel patch.sh. All other commands can be run normally. If you have any trouble running EXPERIMENTAL-stage-1-kernel-patch.sh, just run stage-1-kernel-patch.sh. Both of them work just fine, the EXPERIMENTAL one is a lot faster, though (an hour or more faster.)

Thank you so much @thefloppydriver , later I will try and go back to you with the results 😉.

**Comment by thefloppydriver** [comment] 2022-03-05 20:37
@Special-Niewbie stage-1-kernel-patch.sh now patches kernel instead of rebuilding. Everything is in order and I've merged all the changes. This version is much better!

**Comment by Special-Niewbie** [comment] 2022-03-06 03:17
> @Special-Niewbie stage-1-kernel-patch.sh now patches the current running kernel instead of patching, building, and installing 5.11.22. Everything is in order and I've merged all the changes. This version is much better! Instead of ~3 hours, stage 1 now takes less than 2 minutes.

Hi @thefloppydriver , yesterday I finished late to test it takes me 12 hours......not because of your build but because the machine that I'm testing it's an intel Atom.....

Anyway, I save all the reports, I anticipate to you that the EXPERIMENTAL come out with errors and the normal kernel it start took me 12 hours (so there is some step forward here) but I believe in last minute give me the error of building process.... So both still not working. Let me know if you need those reports, please. Now, you changed and it will patch the current Kernel, I understand well about?

**Comment by thefloppydriver** [comment] 2022-03-06 03:20
@Special-Niewbie Yep, I changed everything out. Try cloning the project again and running ./stage-1-kernel-patch.sh
Tell me how it goes!

**Comment by Special-Niewbie** [comment] 2022-03-06 03:22
> @Special-Niewbie Yep, I changed everything out. Try cloning the project again and running ./stage-1-kernel-patch.sh
> Tell me how it goes!

Perfect, thank you, I will let it to start now in this case because will take awhile with my little PC.....👍

**Comment by Special-Niewbie** [comment] 2022-03-06 03:39
@thefloppydriver , this time make it more fast and still give the error of building as below......

![IMG_20220306_113654.jpg](https://user-images.githubusercontent.com/64843123/156908154-caf32f35-ab42-4d69-bf01-7507b2233283.jpg)

Seems there is some symbol in coding that it doesn't like during the building process.....

**Comment by thefloppydriver** [comment] 2022-03-06 03:39
@Special-Niewbie It's alright! Thanks for testing! It should take less than 5 minutes!

**Comment by thefloppydriver** [comment] 2022-03-06 03:42
It should've generated a text file in the pc2drc directory, could you send that to me?

**Comment by Special-Niewbie** [comment] 2022-03-06 03:44
> @Special-Niewbie It's alright! Thanks for testing! It should take less than 5 minutes!

Below, it's the generated report error.....

![IMG_20220306_114231.jpg](https://user-images.githubusercontent.com/64843123/156908291-a52a8357-379d-4114-a0c4-4058f3d91425.jpg)

**Comment by thefloppydriver** [comment] 2022-03-06 03:47
Could you post the output of `dmesg | grep mac80211`

**Comment by Special-Niewbie** [comment] 2022-03-06 03:50
> Could you post the output of `dmesg | grep mac80211`

Here we go.....

![IMG_20220306_114914.jpg](https://user-images.githubusercontent.com/64843123/156908422-eb2d57f6-882b-44ac-9b5b-e0f31f204aa5.jpg)

**Comment by thefloppydriver** [comment] 2022-03-06 03:54
Strange.

Try rebooting and then running `test -f "/sys/class/net/$(ip link show | grep -o -m1 "\w*wl\w*")/tsf` && echo "it worked!"

Post the output of that command here

**Comment by thefloppydriver** [comment] 2022-03-06 03:57
If that doesn't work, try `sudo modprobe cfg80211` 

and then do `sudo -E ./stage-1-kernel-patch.sh`

**Comment by Special-Niewbie** [comment] 2022-03-06 04:09
> Strange.
> 
> Try rebooting and then running `test -f "/sys/class/net/$(ip link show | grep -o -m1 "\w*wl\w*")/tsf && echo "it worked!"`
> 
> Post the output of that command here 

With this solution, it gives me the below error:

![IMG_20220306_120220.jpg](https://user-images.githubusercontent.com/64843123/156908804-b86a71d7-2ef7-4205-b794-1eb62d4db855.jpg)

Now I'm testing the second solution below , and I need to let it finish the building process....I will report shortly as soon it will finish the process.🤞🏻

**Comment by thefloppydriver** [comment] 2022-03-06 04:14
There are a few typos in your command

try

test -f "/sys/class/$(ip link show | grep -o -m1 "\w*wl\w*")/tsf" && echo "it worked!"

**Comment by thefloppydriver** [comment] 2022-03-06 04:15
also try `sudo depmod -a` if running `sudo -E ./stage-1-kernel-patch.sh` still doesn't work.

**Comment by Special-Niewbie** [comment] 2022-03-06 04:16
> If that doesn't work, try `sudo modprobe cfg80211` 
> 
> and then do `sudo -E ./stage-1-kernel-patch.sh`

With this it gives me the same error as above ( Below , I re- attached the same pic because it's the same error)

![IMG_20220306_114231.jpg](https://user-images.githubusercontent.com/64843123/156908952-4c7d5525-ceec-4732-9eb0-60492b65dbc6.jpg)

Everything I did after rebooting.....

**Comment by thefloppydriver** [comment] 2022-03-06 04:17
> also try `sudo depmod -a` if running `sudo -E ./stage-1-kernel-patch.sh` still doesn't work.

@Special-Niewbie How about this?

**Comment by thefloppydriver** [comment] 2022-03-06 04:18
then running the kernel patch?

**Comment by Special-Niewbie** [comment] 2022-03-06 04:23
> > also try `sudo depmod -a` if running `sudo -E ./stage-1-kernel-patch.sh` still doesn't work.
> 
> @Special-Niewbie How about this?

I'm testing now, sorry but I'm replying with the phone and I'm not in front of my principal PC, be patient that I'm a bit slow here.....

**Comment by thefloppydriver** [comment] 2022-03-06 04:25
@Special-Niewbie Don't worry about it.

**Comment by Special-Niewbie** [comment] 2022-03-06 04:32
> then running the kernel patch?

Ok the "sudo depmod -a" seems okay, but when I run the Kernel Patch file, it gives me the error below: 

![IMG_20220306_122900.jpg](https://user-images.githubusercontent.com/64843123/156909301-342ccd5e-531d-4f21-9f41-0b6da3b3ab57.jpg)

Seems always the same, there is some coding symbols into the mac80211 that it doesn't like to the building process or fr my experience I could miss some libs that allow the compiler to finish the building process.....

**Comment by thefloppydriver** [comment] 2022-03-06 04:35
> There are a few typos in your command
> 
> try
> 
> `test -f "/sys/class/$(ip link show | grep -o -m1 "\w*wl\w*")/tsf" && echo "it worked!"`

Just to confirm, this doesn't work, right?

**Comment by Special-Niewbie** [comment] 2022-03-06 04:36
You see the picture below, after it tells that missing the parameters 

![IMG_20220306_123448.jpg](https://user-images.githubusercontent.com/64843123/156909401-3970c2e5-f216-4cb2-89d1-a228e0581c8d.jpg)

**Comment by Special-Niewbie** [comment] 2022-03-06 04:38
> > There are a few typos in your command
> > 
> > try
> > 
> > `test -f "/sys/class/$(ip link show | grep -o -m1 "\w*wl\w*")/tsf" && echo "it worked!"`
> 
> Just to confirm, this doesn't work, right?
> 
> 

It doesn't work because cannot recognize the last symbol Exclamation point "!". If I take out the Exclamation point , it goes to a second line and waiting me to input some other command

**Comment by thefloppydriver** [comment] 2022-03-06 04:41
> > then running the kernel patch?
> 
> Ok the "sudo depmod -a" seems okay, but when I run the Kernel Patch file, it gives me the error below: 
> 
> ![IMG_20220306_122900.jpg](https://user-images.githubusercontent.com/64843123/156909301-342ccd5e-531d-4f21-9f41-0b6da3b3ab57.jpg)
> 
> Seems always the same, there is some coding symbols into the mac80211 that it doesn't like to the building process or fr my experience I could miss some libs that allow the compiler to finish the building process.....

@Special-Niewbie It's probably an issue involving dkms not having the right Module.symvers for the mac80211.ko module. 

As the error says, I have no idea why this happens.

I'll talk to my uncle about it, he knows this stuff a lot better than I do.

My system configuration is *very* different from yours XD

**Comment by thefloppydriver** [comment] 2022-03-06 04:44
> > > There are a few typos in your command
> > > 
> > > try
> > > 
> > > `test -f "/sys/class/$(ip link show | grep -o -m1 "\w*wl\w*")/tsf" && echo "it worked!"`
> > 
> > Just to confirm, this doesn't work, right?
> > 
> > 
> 
> It doesn't work because cannot recognize the last symbol Exclamation point "!" (After "it worked" word). If I take out the Exclamation point , it goes to a second line and waiting me to input some other command 

That's because of the typo, you didn't put a space between the -o and the -m1 and you didn't put a " at the end of /tsf

**Comment by Special-Niewbie** [comment] 2022-03-06 04:45
> > > then running the kernel patch?
> > 
> > Ok the "sudo depmod -a" seems okay, but when I run the Kernel Patch file, it gives me the error below: 
> > 
> > ![IMG_20220306_122900.jpg](https://user-images.githubusercontent.com/64843123/156909301-342ccd5e-531d-4f21-9f41-0b6da3b3ab57.jpg)
> > 
> > Seems always the same, there is some coding symbols into the mac80211 that it doesn't like to the building process or fr my experience I could miss some libs that allow the compiler to finish the building process.....
> 
> @Special-Niewbie It's probably an issue involving dkms not having the right Module.symvers for the mac80211.ko module. 
> 
> As the error says, I have no idea why this happens.
> 
> I'll talk to my uncle about it, he knows this stuff a lot better than I do.
> 
> My system configuration is *very* different from yours XD

It's okay, because I don't use my principal Ubuntu installation and I use a fresh installation with a testing PC, please let me know if I need to use another OS Distro from Linux? As you said you have totally different configuration, why are you using another Linux Distro?

**Comment by thefloppydriver** [comment] 2022-03-06 04:47
@Special-Niewbie By "system configuration" I mean my physical system configuration, as in the hardware in my PC. 

Do you have secure-boot enabled?

**Comment by thefloppydriver** [comment] 2022-03-06 04:51
@Special-Niewbie Are you using Google translate? "typo" is a way of saying "misspelling"

**Comment by Special-Niewbie** [comment] 2022-03-06 04:54
> @Special-Niewbie Are you using Google translate? "typo" is a way of saying "misspelling"

No, I'm not English native language, and I'm with kids around, testing the machine and write as fast as I can with the phone to give you as soon as possible a report...... Sorry for that😉

**Comment by thefloppydriver** [comment] 2022-03-06 04:59
@Special-Niewbie It's alright! I get it 😂 I'll research this more tomorrow and try to reproduce the issue, but I need to get some rest.

**Comment by Special-Niewbie** [comment] 2022-03-06 05:00
> @Special-Niewbie By "system configuration" I mean my physical system configuration, as in the hardware in my PC. 
> 
> Do you have secure-boot enabled?

I was checking in the BIOS, about the Secure Boot, and this laptop doesn't have even such basic BIOS voice to select. 
So, the unique kind of Secure Boot that I found , was under another name .... now I disabled it, and let's see what will happens.... Otherwise I need to switch with another PC (this time PC Desktop and not notebook) if this still persists me to give this error. Because here you could have right as the Secure Boot maybe enable by default it doesn't allowing with process.....

**Comment by Special-Niewbie** [comment] 2022-03-06 05:05
> @Special-Niewbie It's alright! I get it 😂 I'll research this more tomorrow and try to reproduce the issue, but I need to get some rest. 

Okay, take your time, I will try to prepare another PC for testing, and this afternoon I will go around to find an English Native Writer to write and communicate with you.... 😅😂

**Comment by Stormy178** [comment] 2022-03-06 05:52
I'm currently having similar issues, but instead of inserting the modules, it couldn't find them. I have attached the generated log.txt as well as copied command output (btw it starts after the kernel base as the script works successfully up to that point).
I also have a suggestion of notifying advanced users to open a new terminal if they wish to modify the kernel .config file before continuing
[generated_bug_report.txt](https://github.com/thefloppydriver/pc2drc/files/8192020/generated_bug_report.txt)
[pc2drc-kernelpatch.log](https://github.com/thefloppydriver/pc2drc/files/8192021/pc2drc-kernelpatch.log)

**Comment by thefloppydriver** [comment] 2022-03-06 14:48
> I'm currently having similar issues, but instead of inserting the modules, it couldn't find them. I have attached the generated log.txt as well as copied command output (btw it starts after the kernel base as the script works successfully up to that point).
> I also have a suggestion of notifying advanced users to open a new terminal if they wish to modify the kernel .config file before continuing
> QUICK EDIT! I should also mention I'm running Pop!OS 21.10 on kernel version 5.16.11
> 
> [generated_bug_report.txt](https://github.com/thefloppydriver/pc2drc/files/8192020/generated_bug_report.txt)
> [pc2drc-kernelpatch.log](https://github.com/thefloppydriver/pc2drc/files/8192021/pc2drc-kernelpatch.log)
> 

@Stormy178 Thanks for sharing! 
Could you try running `test -f "/sys/class/$(ip link show | grep -o -m1 '\w*wl\w*')/tsf" && echo "it worked!"`

**Comment by thefloppydriver** [comment] 2022-03-06 16:21
> I'm currently having similar issues, but instead of inserting the modules, it couldn't find them. I have attached the generated log.txt as well as copied command output (btw it starts after the kernel base as the script works successfully up to that point). I also have a suggestion of notifying advanced users to open a new terminal if they wish to modify the kernel .config file before continuing QUICK EDIT! I should also mention I'm running Pop!OS 21.10 on kernel version 5.16.11
> 
> [generated_bug_report.txt](https://github.com/thefloppydriver/pc2drc/files/8192020/generated_bug_report.txt) [pc2drc-kernelpatch.log](https://github.com/thefloppydriver/pc2drc/files/8192021/pc2drc-kernelpatch.log)

@Stormy178 SIGH. I wish Ubuntu made it easy to programmatically grab their kernel sources, because there are sometimes breaking changes between the unmodified linux kernel version and the ubuntu linux kernel version. Try running `sudo -E ./kernel-patch-files/build-patched-kernel.sh` until I figure out a good solution :)

(P.S. I'm not claiming support for PopOS or 21.04 :joy:, I usually stick to LTS versions of Ubuntu)

**Comment by thefloppydriver** [comment] 2022-03-06 16:52
I'm going to add some steps that instruct the user to get their kernel sources and put them in the kernel-patch-files directory under the name, "linux-kernel-sources"

I hate doing it this way but it's the only way to guarantee that the kernel patch works. I should have it pushed by the end of the day. Sorry things turned out this way!

**Comment by thefloppydriver** [comment] 2022-03-06 23:11
> I'm going to add some steps that instruct the user to get their kernel sources and put them in the kernel-patch-files directory under the name, "linux-kernel-sources"
> 
> I hate doing it this way but it's the only way to guarantee that the kernel patch works. I should have it pushed by the end of the day. Sorry things turned out this way!

@Stormy178 
Well! I did it! Try deleting the repo and trying again with a fresh cloned version!

**Comment by Special-Niewbie** [comment] 2022-03-07 03:33
@thefloppydriver , I'm still trying to build it in the old notebook with your latest code changes.  

There is a small step forward, but it still gives me an error, I attach the photo below:

![Schermata da 2022-03-07 11-01-27.png](https://user-images.githubusercontent.com/64843123/156963261-972ea7c5-8936-42f7-969c-2087945a7374.png)


Now, I have run the second function Optional .... / kernel-patch-files / .... if that also doesn't work, I will try to change the PC, I still haven't changed PC for this test because it takes me some time to prepare it with a fresh Linux installation.  

In the meantime, I noticed 3 error warnings that maybe you might be interested in, you can find them below in this other image, the error tells about of the "m" symbol value (maybe it's useful for you or maybe not, but I just trying to give you any feedback to help even if could be useless).....

![IMG_20220307_112901.jpg](https://user-images.githubusercontent.com/64843123/156963290-031e1ed9-3dcf-45e1-8814-840c53754cf5.jpg)

**Comment by thefloppydriver** [comment] 2022-03-07 04:15
@Special-Niewbie Thanks for trying it out! That 'm' warning is harmless :)

Could you send me a screenshot of the output of
`cat /var/lib/dkms/drc-mac80211/0.1.0/5.13.0-30-generic/x86_64/log/make.log`
or attach the file?

**Comment by Special-Niewbie** [comment] 2022-03-07 04:27
> @Special-Niewbie Thanks for trying it out! That 'm' warning is harmless :)
> 
> Could you send me a screenshot of the output of `cat /var/lib/dkms/drc-mac80211/0.1.0/5.13.0-30-generic/x86_64/log/make.log` or attach the file?

I have attached the "make.log" file below.......
[make.log](https://github.com/thefloppydriver/pc2drc/files/8194823/make.log)

**Comment by thefloppydriver** [comment] 2022-03-07 04:33
Looks the same as mine, it should be working I don't know why it isn't :sweat_smile:
Try rebooting and then running the command below
`modprobe mac80211 && test -f "/sys/class/net/$(ip link show | grep -o -m1 "\w*wl\w*")/tsf" && echo "Hooray!"`

If it outputs "Hooray!" then you should be able to run stage-2

**Comment by Special-Niewbie** [comment] 2022-03-07 04:46
> Looks the same as mine, it should be working I don't know why it isn't 😅 Try rebooting and then running the command below `modprobe mac80211 && test -f "/sys/class/net/$(ip link show | grep -o -m1 "\w*wl\w*")/tsf" && echo "Hooray!"`
> 
> If it outputs "Hooray!" then you should be able to run stage-2

Ok, in this case I stop the process I started with the `sudo -E ./kernel-patch-files/build-patched-kernel.sh` function, and try to do as you say.
It seems that I have found the problems related to this problem, and it seems that the problem it is in between the SIGN DRIVER and the SECURE BOOT.

I'll give you these two Posts:
1)  https://askubuntu.com/questions/1348250/skipping-btf-generation-xxx-due-to-unavailability-of-vmlunux-on-ubuntu-21-04-ge

2)  https://github.com/mkubecek/vmware-host-modules/issues/87#issuecomment-800051833

  But as I told you, this notebook does not have SECURE BOOT as an option to disable it and the BIOS is in Legacy and not in UEFI.

**Comment by thefloppydriver** [comment] 2022-03-07 04:53
I see! That's odd as all computers that I've seen have had a secure boot option. Maybe it's buried somewhere in the BIOS settings or called something different, it could be Intel TPM

**Comment by Special-Niewbie** [comment] 2022-03-07 06:17
> I see! That's odd as all computers that I've seen have had a secure boot option. Maybe it's buried somewhere in the BIOS settings or called something different, it could be Intel TPM

Yes it's really odd, also for me it's first time to see a PC/notebook without Secure Boot , TPM or what so ever. 

This notebook I took from someone that was going to drop to the trash bin. 
So, I use it just for tests...the unique voice in the Bios that Samsung made (as a Secure Boot) they calls EDB (Execute Disable Bit), I already disable it. 

To update you, finally after another reboot I can install the patch but with modprob error, please look the picture below:

![IMG_20220307_134336.jpg](https://user-images.githubusercontent.com/64843123/156978461-15b56d65-15ff-45b3-bb31-3273ccb61f64.jpg)

**Comment by thefloppydriver** [comment] 2022-03-07 06:34
@Special-Niewbie That's really strange. I'll leave this issue open in case someone comes up with a good solution, but because I can't reproduce the error on my machine I'd suggest using another PC for this project because I can't guarantee that I'll have a fix for this anytime soon. Sorry for your troubles.

**Comment by Special-Niewbie** [comment] 2022-03-07 06:39
> @Special-Niewbie That's really strange. I'll leave this issue open in case someone comes up with a good solution, but because I can't reproduce the error on my machine I'd suggest using another PC for this project because I can't guarantee that I'll have a fix for this anytime soon. Sorry for your troubles. 

It's okay man , no sorry, I just try to help here.

I will try with another PC.

Last question, in another PC, can I install and test it with latest Ubuntu Version 21.10 or I must to use the Ubuntu LTS 20.04 version?

**Comment by thefloppydriver** [comment] 2022-03-07 06:45
@Special-Niewbie You can try with Ubuntu Version 21.10, nothing will break that can't be fixed, but just know that you'd be the first to try it ;)

**Comment by thefloppydriver** [comment] 2022-03-07 19:53
@Special-Niewbie I added better error reporting to stage-1-kernel-patch. I suspect that your wireless driver ( #2 ) doesn't support mac80211. Would you mind cloning the repo again and running stage-1-kernel-patch to confirm this?

It should say something like, "No devices were using mac80211. You might not be using a compatible wifi interface"

**Comment by Special-Niewbie** [comment] 2022-03-08 03:09
> @Special-Niewbie I added better error reporting to stage-1-kernel-patch. I suspect that your wireless driver ( #2 ) doesn't support mac80211. Would you mind cloning the repo again and running stage-1-kernel-patch to confirm this?
> 
> It should say something like, "No devices were using mac80211. You might not be using a compatible wifi interface"

Ok, I'm downloading and testing right now..... But, I thought that the patch mac80211 was anyway apply in the first stage, this doesn't matter if compatible or not the hardware.....I was mistaken to thinking in this way?

**Comment by Special-Niewbie** [comment] 2022-03-08 03:19
Okay, the results come out as you modify the coding, please watch the pic below:

![2022-03-07 11-01-27.png](https://user-images.githubusercontent.com/64843123/157159550-4c1728c5-796e-43f1-bb73-8250073a77c3.png)

This it means that I need to suspend any testing, till I will not find the compatible mac80211 USB WiFi adapter hardware?

**Comment by thefloppydriver** [comment] 2022-03-08 03:44
> > @Special-Niewbie I added better error reporting to stage-1-kernel-patch. I suspect that your wireless driver ( #2 ) doesn't support mac80211. Would you mind cloning the repo again and running stage-1-kernel-patch to confirm this?
> > It should say something like, "No devices were using mac80211. You might not be using a compatible wifi interface"
> 
> Ok, I'm downloading and testing right now..... But, I thought that the patch mac80211 was anyway apply in the first stage, this doesn't matter if compatible or not the hardware.....I was mistaken to thinking in this way?

The kernel patch *installs,* but the final check in the script doesn't work because there aren't any mac80211 compatible devices installed. You can continue testing, but stage-3 and stage-4 won't work.

I just added a command line option to stage-2, --no-check-tsf

clone the repository again and run stage-0, then stage-1, then stage-2 BUT when you run stage-2 run it like this:
`sudo -E stage-2-build-modules.sh --no-check-tsf`

**Comment by thefloppydriver** [comment] 2022-03-08 03:49
> @

@Special-Niewbie You don't need to suspend testing. The kernel patch creates a tsf file on all mac80211 compatible devices *even if they don't support get_tsf*. However, if you're using a device which doesn't use mac80211 at all (such as the device that you're using), the tsf file will not be created and the final check will fail.

running `sudo -E ./stage-2-build-modules.sh --no-check-tsf` skips the check for the tsf file (the script only does that check to make sure stage-1 worked (which it did) so removing it by passing --no-check-tsf is harmless.)

**Comment by Special-Niewbie** [comment] 2022-03-08 03:53
> > @
> 
> @Special-Niewbie You don't need to suspend testing. The kernel patch creates a tsf file on all mac80211 compatible devices *even if they don't support get_tsf*. However, if you're using a device which doesn't use mac80211 at all (such as the device that you're using), the tsf file will not be created and the final check will fail.
> 
> running `sudo -E ./stage-2-build-modules.sh --no-check-tsf` skips the check for the tsf file (the script only does that check to make sure stage-1 worked (which it did) so removing it by passing --no-check-tsf is harmless.)

For me as soon we understand that the stages installation are working fine now, I'm okay.... anyway in the end if I cannot use any of my usb adapters I need to check to buy a new usb WiFi compatibile with it. 

Thank you so much for supporting @thefloppydriver

**Comment by thefloppydriver** [comment] 2022-03-08 03:56
> 

Thanks for testing! I'm afraid that you'll have to go out of your way to buy a compatible wifi device :/

**Comment by thefloppydriver** [comment] 2022-03-08 03:57
> > > @
> > 
> > 
> > @Special-Niewbie You don't need to suspend testing. The kernel patch creates a tsf file on all mac80211 compatible devices _even if they don't support get_tsf_. However, if you're using a device which doesn't use mac80211 at all (such as the device that you're using), the tsf file will not be created and the final check will fail.
> > running `sudo -E ./stage-2-build-modules.sh --no-check-tsf` skips the check for the tsf file (the script only does that check to make sure stage-1 worked (which it did) so removing it by passing --no-check-tsf is harmless.)
> 
> For me as soon we understand that the stages installation are working fine now, I'm okay.... anyway in the end if I cannot use any of my usb adapters I need to check to buy a new usb WiFi compatibile with it.
> 
> Thank you so much for supporting @thefloppydriver

@Special-Niewbie 
Thanks for testing! I'm afraid that you'll have to go out of your way to buy a compatible wifi device :/

**Comment by Special-Niewbie** [comment] 2022-03-08 04:03
> > > > @
> > > 
> > > 
> > > @Special-Niewbie You don't need to suspend testing. The kernel patch creates a tsf file on all mac80211 compatible devices _even if they don't support get_tsf_. However, if you're using a device which doesn't use mac80211 at all (such as the device that you're using), the tsf file will not be created and the final check will fail.
> > > running `sudo -E ./stage-2-build-modules.sh --no-check-tsf` skips the check for the tsf file (the script only does that check to make sure stage-1 worked (which it did) so removing it by passing --no-check-tsf is harmless.)
> > 
> > For me as soon we understand that the stages installation are working fine now, I'm okay.... anyway in the end if I cannot use any of my usb adapters I need to check to buy a new usb WiFi compatibile with it.
> > 
> > Thank you so much for supporting @thefloppydriver
> 
> @Special-Niewbie 
> Thanks for testing! I'm afraid that you'll have to go out of your way to buy a compatible wifi device :/

As soon I can support you with this amazing project, one usb to buy it's the minimum. But I need to wait and find it, if you have any other models to suggest me you are welcome to do it.

**Comment by thefloppydriver** [comment] 2022-03-08 04:08
@Special-Niewbie 
https://www.walmart.com/ip/300Mbps-Wifi-Adapter-Black-Wireless-Network-Card-RT5572-2-4G-5G-Office-Dual-Band/270210880?wmlspartner=wlpa&selectedSellerId=101121245

You can find a whole bunch of the device that you need by looking here https://www.google.com/search?q=rt5572&tbm=shop

**Closed** 2022-04-17 03:46 UTC
Labels: bug
